# Serverless Configuration
org: snarjun98
app: serverless-crud-api
service: serverless-crud-api
frameworkVersion: "3"
configValidationMode: error
useDotenv: true

# AWS Provider Configuration
provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  stage: ${opt:stage, 'dev'}
  region:
    "ap-south-1"
    # functions config
  versionFunctions: false
  timeout: 10
  environment:
    NOTES_TABLE_NAME: ${self:custom.notesTableName}
    USERS_TABLE_NAME: ${self:custom.usersTableName}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict IAM role permissions to specific tables for the stage
      Resource:
        - "Fn::GetAtt": [NotesTable, Arn]
        - "Fn::GetAtt": [UsersTable, Arn]
# Custom Configuration
custom:
  # Prefix for naming resources
  prefix: ${self:service}
  # DynamoDB table names
  notesTableName: "notes-${self:provider.stage}"
  usersTableName: "users-${self:provider.stage}"

# AWS Lambda Functions
functions:
  - ${file(resource/functions/notes/note-functions.yml)}

# AWS Resources (DDB resources)
resources:
  - ${file(resource/dynamodb/notes.yml)}
  - ${file(resource/dynamodb/users.yml)}
